server:
  port: 8080
# 端点放开用于检测信息
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端口
    #enabled-by-default: true # 启用所有端口
  endpoint:
    health:
      show-details: always
#com:
#  sun:
#    management:
#      jmxremote:
#        authenticate: false;
#        port: 9999;
#        ssl: false;
#      jmxremote;: