eureka:
  server:
    #生产环境需打开保护机制
    enable-self-preservation: false       #关闭保护机制，以确保注册中心可以将不可用的实例剔除.(注意：自我保护模式是一种应对网络异常的安全保护措施,使用自我保护模式，可以让Eureka集群更加的健壮、稳定)
    eviction-interval-timer-in-ms: 60000 #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false
    # 是否从eureka上获取注册信息
    fetch-registry: false
    serviceUrl:
      #多个注册中心填写其他注册中心地址
#      defaultZone: http://eureka2:1002/eureka/
      #单个注册中心填写自身地址
      defaultZone: http://localhost:8087/eureka/